basic-config:

  name: demo-app-helm

  image: quay.io/calopezb/argo-demo-app:1.0

  replicas: 3

  port: 8080

  routeEnabled: true

  config:
    enabled: true
    data:
      APP_ENVIRONMENT: "OpenShift (demo-helm)"
      APP_NAME: "Demo App using Helm and Argo"
      APP_VERSION: "1.0"

  secret:
    enabled: true
    data:
      APP_SECRET: "super secret value from helm in argo"